### ISSUE TITLE
Could you provide the requirements of the project? Thanks so much.

### ISSUE THREAD

**Issue by JodieYoung** [yanweiyue/MoG#1]

**Comment by yanweiyue** [comment]
Of course, the requirements of the project are:
networkit==11.0
networkx==2.5.1
numpy==1.19.5
ogb==1.3.6
pandas==1.1.5
scikit_learn==1.5.1
scipy==1.5.4
torch==2.3.1
torch_geometric==1.6.3
torch_scatter==2.1.2
tqdm==4.64.1
traitlets==4.3.3
