### ISSUE TITLE
Pruning Criteria

### ISSUE THREAD

**Issue by gray-sunflower** [yanweiyue/MoG#2]
Hi, i have read your paper and i can't seem to find the pruning criteria part that presented in the paper (Degree, Jaccard, ER, ...) in the codes. Thanks you for reading, I look forward to your response.

**Comment by yanweiyue** [comment]
Thank you very much for your attention to our work and for your thorough review of the code. Regarding the "pruning criteria part that is presented in the paper (Degree, Jaccard, ER, ...)" that you mentioned, you can refer to the `get_topo_val` function found here: https://github.com/yanweiyue/MoG/blob/243be7d6857e05175fb6687e2c0021deb45bfce3/ogbn_proteins/MoE.py#L241-L257
This function calculates the topological pruning criteria for each edge (Degree, Jaccard, ER, etc.). I sincerely hope this response can address your concerns.
